In [1]:
import pandas as pd

# DateTime Conversion

In [2]:
# clean_data datetime parsing -> client_df
client_df = pd.read_csv('clean_data.csv', parse_dates=[5, 6, 7, 8])
display(client_df.head())
display(client_df.info())

# price_data datetime parsing -> price_df
price_df = pd.read_csv('price_data.csv', parse_dates=[1])
display(price_df.head())
display(price_df.info())

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,...,0.000131,4.100838e-05,9.084737e-04,2.086294,99.530517,44.235794,2.086425,9.953056e+01,4.423670e+01,1
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,...,0.000003,1.217891e-03,0.000000e+00,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,...,0.000004,9.450150e-08,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0
3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,...,0.000003,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0
4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,...,0.000011,2.896760e-06,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14606 entries, 0 to 14605
Data columns (total 44 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              14606 non-null  object
 1   channel_sales                   14606 non-null  object
 2   cons_12m                        14606 non-null  int64
 3   cons_gas_12m                    14606 non-null  int64
 4   cons_last_month                 14606 non-null  int64
 5   date_activ                      14606 non-null  datetime64[ns]
 6   date_end                        14606 non-null  datetime64[ns]
 7   date_modif_prod                 14606 non-null  datetime64[ns]
 8   date_renewal                    14606 non-null  datetime64[ns]
 9   forecast_cons_12m               14606 non-null  float64
 10  forecast_cons_year              14606 non-null  int64
 11  forecast_discount_energy        14606 non-null  float64
 12  forecast_meter_rent_12m         14606 non-null  float64
 13  forecast_price_energy_off_peak  14606 non-null  float64
 14  forecast_price_energy_peak      14606 non-null  float64
 15  forecast_price_pow_off_peak     14606 non-null  float64
 16  has_gas                         14606 non-null  object
 17  imp_cons                        14606 non-null  float64
 18  margin_gross_pow_ele            14606 non-null  float64
 19  margin_net_pow_ele              14606 non-null  float64
 20  nb_prod_act                     14606 non-null  int64
 21  net_margin                      14606 non-null  float64
 22  num_years_antig                 14606 non-null  int64
 23  origin_up                       14606 non-null  object
 24  pow_max                         14606 non-null  float64
 25  var_year_price_off_peak_var     14606 non-null  float64
 26  var_year_price_peak_var         14606 non-null  float64
 27  var_year_price_mid_peak_var     14606 non-null  float64
 28  var_year_price_off_peak_fix     14606 non-null  float64
 29  var_year_price_peak_fix         14606 non-null  float64
 30  var_year_price_mid_peak_fix     14606 non-null  float64
 31  var_year_price_off_peak         14606 non-null  float64
 32  var_year_price_peak             14606 non-null  float64
 33  var_year_price_mid_peak         14606 non-null  float64
 34  var_6m_price_off_peak_var       14606 non-null  float64
 35  var_6m_price_peak_var           14606 non-null  float64
 36  var_6m_price_mid_peak_var       14606 non-null  float64
 37  var_6m_price_off_peak_fix       14606 non-null  float64
 38  var_6m_price_peak_fix           14606 non-null  float64
 39  var_6m_price_mid_peak_fix       14606 non-null  float64
 40  var_6m_price_off_peak           14606 non-null  float64
 41  var_6m_price_peak               14606 non-null  float64
 42  var_6m_price_mid_peak           14606 non-null  float64
 43  churn                           14606 non-null  int64
dtypes: datetime64[ns](4), float64(29), int64(7), object(4)
memory usage: 4.9+ MB

None

,id,price_date,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix
0,038af19179925da21a25619c5a24b745,2015-01-01,0.151367,0.0,0.0,44.266931,0.0,0.0
1,038af19179925da21a25619c5a24b745,2015-02-01,0.151367,0.0,0.0,44.266931,0.0,0.0
2,038af19179925da21a25619c5a24b745,2015-03-01,0.151367,0.0,0.0,44.266931,0.0,0.0
3,038af19179925da21a25619c5a24b745,2015-04-01,0.149626,0.0,0.0,44.266931,0.0,0.0
4,038af19179925da21a25619c5a24b745,2015-05-01,0.149626,0.0,0.0,44.266931,0.0,0.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193002 entries, 0 to 193001
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  193002 non-null  object
 1   price_date          193002 non-null  datetime64[ns]
 2   price_off_peak_var  193002 non-null  float64
 3   price_peak_var      193002 non-null  float64
 4   price_mid_peak_var  193002 non-null  float64
 5   price_off_peak_fix  193002 non-null  float64
 6   price_peak_fix      193002 non-null  float64
 7   price_mid_peak_fix  193002 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 11.8+ MB

None

# Feature Engineering

1. off-peak price diff (dec - jan)
2. mid-peak price diff (dec - jan)
3. on-peak price diff (dec - jan)
4. peak spread dec (on peak - off peak)
5. peak spread jan (on peak -  off peak)
6. aggregatte diff (on + mid + off)_dec - (on + mid+ off)_jan

In [3]:
# extract month from price_date
price_df['month'] = price_df['price_date'].dt.month

# numerical features for pivot table
features = ['price_off_peak_var', 'price_off_peak_fix', 'price_mid_peak_var', 'price_mid_peak_fix',
            'price_peak_var', 'price_peak_fix']

# conversion from long to wide format
monthly_data = price_df.pivot_table(
    index='id',
    columns='month',
    values=features,
)

- We have converted the **['price_date']** column to month only, seeing as *our data spans only 1 year*, this brings our price data to closely matching the *length* of our client df. With each row representing one client, and all price info being represented by numbered columns.

In [4]:
#display(monthly_data.sample(15))
print(monthly_data.info())
print(f'\nNUM ROWS WITH AT LEAST ONE MISSING VALUE: {monthly_data.isna().any(axis=1).sum()}\n')

nan_ids = monthly_data[monthly_data.isna().any(axis=1)].index
missing = client_df[client_df['id'].isin(nan_ids)][['id', 'churn']]

print(f'\nMISSING VALUES COMPOSITION:\n{missing['churn'].value_counts()}\n')

monthly_data = monthly_data.dropna()

print(monthly_data.info())
print(f'\nNUM ROWS WITH AT LEAST ONE MISSING VALUE: {monthly_data.isna().any(axis=1).sum()}')

<class 'pandas.core.frame.DataFrame'>
Index: 16096 entries, 0002203ffbb812588b632b9e628cc38d to ffff7fa066f1fb305ae285bb03bf325a
Data columns (total 72 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   (price_mid_peak_fix, 1)   16070 non-null  float64
 1   (price_mid_peak_fix, 2)   16082 non-null  float64
 2   (price_mid_peak_fix, 3)   16074 non-null  float64
 3   (price_mid_peak_fix, 4)   16079 non-null  float64
 4   (price_mid_peak_fix, 5)   16080 non-null  float64
 5   (price_mid_peak_fix, 6)   16085 non-null  float64
 6   (price_mid_peak_fix, 7)   16090 non-null  float64
 7   (price_mid_peak_fix, 8)   16094 non-null  float64
 8   (price_mid_peak_fix, 9)   16082 non-null  float64
 9   (price_mid_peak_fix, 10)  16085 non-null  float64
 10  (price_mid_peak_fix, 11)  16087 non-null  float64
 11  (price_mid_peak_fix, 12)  16094 non-null  float64
 12  (price_mid_peak_var, 1)   16070 non-null  float64
 13  (price_mid_peak_var, 2)   16082 non-null  float64
 14  (price_mid_peak_var, 3)   16074 non-null  float64
 15  (price_mid_peak_var, 4)   16079 non-null  float64
 16  (price_mid_peak_var, 5)   16080 non-null  float64
 17  (price_mid_peak_var, 6)   16085 non-null  float64
 18  (price_mid_peak_var, 7)   16090 non-null  float64
 19  (price_mid_peak_var, 8)   16094 non-null  float64
 20  (price_mid_peak_var, 9)   16082 non-null  float64
 21  (price_mid_peak_var, 10)  16085 non-null  float64
 22  (price_mid_peak_var, 11)  16087 non-null  float64
 23  (price_mid_peak_var, 12)  16094 non-null  float64
 24  (price_off_peak_fix, 1)   16070 non-null  float64
 25  (price_off_peak_fix, 2)   16082 non-null  float64
 26  (price_off_peak_fix, 3)   16074 non-null  float64
 27  (price_off_peak_fix, 4)   16079 non-null  float64
 28  (price_off_peak_fix, 5)   16080 non-null  float64
 29  (price_off_peak_fix, 6)   16085 non-null  float64
 30  (price_off_peak_fix, 7)   16090 non-null  float64
 31  (price_off_peak_fix, 8)   16094 non-null  float64
 32  (price_off_peak_fix, 9)   16082 non-null  float64
 33  (price_off_peak_fix, 10)  16085 non-null  float64
 34  (price_off_peak_fix, 11)  16087 non-null  float64
 35  (price_off_peak_fix, 12)  16094 non-null  float64
 36  (price_off_peak_var, 1)   16070 non-null  float64
 37  (price_off_peak_var, 2)   16082 non-null  float64
 38  (price_off_peak_var, 3)   16074 non-null  float64
 39  (price_off_peak_var, 4)   16079 non-null  float64
 40  (price_off_peak_var, 5)   16080 non-null  float64
 41  (price_off_peak_var, 6)   16085 non-null  float64
 42  (price_off_peak_var, 7)   16090 non-null  float64
 43  (price_off_peak_var, 8)   16094 non-null  float64
 44  (price_off_peak_var, 9)   16082 non-null  float64
 45  (price_off_peak_var, 10)  16085 non-null  float64
 46  (price_off_peak_var, 11)  16087 non-null  float64
 47  (price_off_peak_var, 12)  16094 non-null  float64
 48  (price_peak_fix, 1)       16070 non-null  float64
 49  (price_peak_fix, 2)       16082 non-null  float64
 50  (price_peak_fix, 3)       16074 non-null  float64
 51  (price_peak_fix, 4)       16079 non-null  float64
 52  (price_peak_fix, 5)       16080 non-null  float64
 53  (price_peak_fix, 6)       16085 non-null  float64
 54  (price_peak_fix, 7)       16090 non-null  float64
 55  (price_peak_fix, 8)       16094 non-null  float64
 56  (price_peak_fix, 9)       16082 non-null  float64
 57  (price_peak_fix, 10)      16085 non-null  float64
 58  (price_peak_fix, 11)      16087 non-null  float64
 59  (price_peak_fix, 12)      16094 non-null  float64
 60  (price_peak_var, 1)       16070 non-null  float64
 61  (price_peak_var, 2)       16082 non-null  float64
 62  (price_peak_var, 3)       16074 non-null  float64
 63  (price_peak_var, 4)       16079 non-null  float64
 64  (price_peak_var, 5)       16080 non-null  float64
 65  (price_peak_var, 6)       16085 non-null  float64
 66  (price_peak_var, 7)       16090 non-null  float64
 67  (price_peak_var, 8)       16094 non-null  float64
 68  (price_peak_var, 9)       16082 non-null  float64
 69  (price_peak_var, 10)      16085 non-null  float64
 70  (price_peak_var, 11)      16087 non-null  float64
 71  (price_peak_var, 12)      16094 non-null  float64
dtypes: float64(72)
memory usage: 9.0+ MB
None

NUM ROWS WITH AT LEAST ONE MISSING VALUE: 106


MISSING VALUES COMPOSITION:
churn
0    68
1    20
Name: count, dtype: int64

<class 'pandas.core.frame.DataFrame'>
Index: 15990 entries, 0002203ffbb812588b632b9e628cc38d to ffff7fa066f1fb305ae285bb03bf325a
Data columns (total 72 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   (price_mid_peak_fix, 1)   15990 non-null  float64
 1   (price_mid_peak_fix, 2)   15990 non-null  float64
 2   (price_mid_peak_fix, 3)   15990 non-null  float64
 3   (price_mid_peak_fix, 4)   15990 non-null  float64
 4   (price_mid_peak_fix, 5)   15990 non-null  float64
 5   (price_mid_peak_fix, 6)   15990 non-null  float64
 6   (price_mid_peak_fix, 7)   15990 non-null  float64
 7   (price_mid_peak_fix, 8)   15990 non-null  float64
 8   (price_mid_peak_fix, 9)   15990 non-null  float64
 9   (price_mid_peak_fix, 10)  15990 non-null  float64
 10  (price_mid_peak_fix, 11)  15990 non-null  float64
 11  (price_mid_peak_fix, 12)  15990 non-null  float64
 12  (price_mid_peak_var, 1)   15990 non-null  float64
 13  (price_mid_peak_var, 2)   15990 non-null  float64
 14  (price_mid_peak_var, 3)   15990 non-null  float64
 15  (price_mid_peak_var, 4)   15990 non-null  float64
 16  (price_mid_peak_var, 5)   15990 non-null  float64
 17  (price_mid_peak_var, 6)   15990 non-null  float64
 18  (price_mid_peak_var, 7)   15990 non-null  float64
 19  (price_mid_peak_var, 8)   15990 non-null  float64
 20  (price_mid_peak_var, 9)   15990 non-null  float64
 21  (price_mid_peak_var, 10)  15990 non-null  float64
 22  (price_mid_peak_var, 11)  15990 non-null  float64
 23  (price_mid_peak_var, 12)  15990 non-null  float64
 24  (price_off_peak_fix, 1)   15990 non-null  float64
 25  (price_off_peak_fix, 2)   15990 non-null  float64
 26  (price_off_peak_fix, 3)   15990 non-null  float64
 27  (price_off_peak_fix, 4)   15990 non-null  float64
 28  (price_off_peak_fix, 5)   15990 non-null  float64
 29  (price_off_peak_fix, 6)   15990 non-null  float64
 30  (price_off_peak_fix, 7)   15990 non-null  float64
 31  (price_off_peak_fix, 8)   15990 non-null  float64
 32  (price_off_peak_fix, 9)   15990 non-null  float64
 33  (price_off_peak_fix, 10)  15990 non-null  float64
 34  (price_off_peak_fix, 11)  15990 non-null  float64
 35  (price_off_peak_fix, 12)  15990 non-null  float64
 36  (price_off_peak_var, 1)   15990 non-null  float64
 37  (price_off_peak_var, 2)   15990 non-null  float64
 38  (price_off_peak_var, 3)   15990 non-null  float64
 39  (price_off_peak_var, 4)   15990 non-null  float64
 40  (price_off_peak_var, 5)   15990 non-null  float64
 41  (price_off_peak_var, 6)   15990 non-null  float64
 42  (price_off_peak_var, 7)   15990 non-null  float64
 43  (price_off_peak_var, 8)   15990 non-null  float64
 44  (price_off_peak_var, 9)   15990 non-null  float64
 45  (price_off_peak_var, 10)  15990 non-null  float64
 46  (price_off_peak_var, 11)  15990 non-null  float64
 47  (price_off_peak_var, 12)  15990 non-null  float64
 48  (price_peak_fix, 1)       15990 non-null  float64
 49  (price_peak_fix, 2)       15990 non-null  float64
 50  (price_peak_fix, 3)       15990 non-null  float64
 51  (price_peak_fix, 4)       15990 non-null  float64
 52  (price_peak_fix, 5)       15990 non-null  float64
 53  (price_peak_fix, 6)       15990 non-null  float64
 54  (price_peak_fix, 7)       15990 non-null  float64
 55  (price_peak_fix, 8)       15990 non-null  float64
 56  (price_peak_fix, 9)       15990 non-null  float64
 57  (price_peak_fix, 10)      15990 non-null  float64
 58  (price_peak_fix, 11)      15990 non-null  float64
 59  (price_peak_fix, 12)      15990 non-null  float64
 60  (price_peak_var, 1)       15990 non-null  float64
 61  (price_peak_var, 2)       15990 non-null  float64
 62  (price_peak_var, 3)       15990 non-null  float64
 63  (price_peak_var, 4)       15990 non-null  float64
 64  (price_peak_var, 5)       15990 non-null  float64
 65  (price_peak_var, 6)       15990 non-null  float64
 66  (price_peak_var, 7)       15990 non-null  float64
 67  (price_peak_var, 8)       15990 non-null  float64
 68  (price_peak_var, 9)       15990 non-null  float64
 69  (price_peak_var, 10)      15990 non-null  float64
 70  (price_peak_var, 11)      15990 non-null  float64
 71  (price_peak_var, 12)      15990 non-null  float64
dtypes: float64(72)
memory usage: 8.9+ MB
None

NUM ROWS WITH AT LEAST ONE MISSING VALUE: 0

- The months of August and December have the highest number of non-null entries across all pricing variables. Pointing towards these months having the highest reliability and retention rates. With January and March having the lowest number of non-null entries, suggesting the inverse.

- Out of 106 rows with at least one missing value, 68 are active customers, and 20 are inactive. This leaves 18 observations that do not have an ID match with client data. This checks out, because client_data has 1,490 less ID's than price_data. Meaning some of the missing value observations are present only within price_data.

- Since the missing values that do match are majority active users, we will be removing all rows that have at least one missing entry. This will provide us with complete and reliable customer data for the entire observational window of 1 year.

In [5]:
# year over year january to december off-peak price differences
monthly_data['dec_jan_off_peak_diff_fix'] = monthly_data['price_off_peak_fix'][12] - monthly_data['price_off_peak_fix'][1]
monthly_data['dec_jan_off_peak_diff_var'] = monthly_data['price_off_peak_var'][12] - monthly_data['price_off_peak_var'][1]

# year over year january to december mid-peak price differences
monthly_data['dec_jan_mid_peak_diff_fix'] = monthly_data['price_mid_peak_fix'][12] - monthly_data['price_mid_peak_fix'][1]
monthly_data['dec_jan_mid_peak_diff_var'] = monthly_data['price_mid_peak_var'][12] - monthly_data['price_mid_peak_var'][1]

# year over year january to december peak price differences
monthly_data['dec_jan_peak_diff_fix'] = monthly_data['price_peak_fix'][12] - monthly_data['price_peak_fix'][1]
monthly_data['dec_jan_peak_diff_var'] = monthly_data['price_peak_var'][12] - monthly_data['price_peak_var'][1]

# dec peak price differences
monthly_data['peak_off_peak_dec_diff_fix'] = monthly_data['price_peak_fix'][12] - monthly_data['price_off_peak_fix'][12]
monthly_data['peak_off_peak_dec_diff_var'] = monthly_data['price_peak_var'][12] - monthly_data['price_off_peak_var'][12]

# jan peak price differences
monthly_data['peak_off_peak_jan_diff_fix'] = monthly_data['price_peak_fix'][1] - monthly_data['price_off_peak_fix'][1]
monthly_data['peak_off_peak_jan_diff_var'] = monthly_data['price_peak_var'][1] - monthly_data['price_off_peak_var'][1]

# aggregate dec price differences
monthly_data['dec_jan_agg_diff_fix'] = ((monthly_data['price_peak_fix'] + monthly_data['price_mid_peak_fix'] + monthly_data['price_off_peak_fix'])[12]
                                        - (monthly_data['price_peak_fix'] + monthly_data['price_mid_peak_fix'] + monthly_data['price_off_peak_fix'])[1])
monthly_data['dec_jan_agg_diff_var'] = ((monthly_data['price_peak_var'] + monthly_data['price_mid_peak_var'] + monthly_data['price_off_peak_var'])[12]
                                        - (monthly_data['price_peak_var'] + monthly_data['price_mid_peak_var'] + monthly_data['price_off_peak_var'])[1])

# summer shock diff (jan to june)
monthly_data['summer_shock_diff_fix'] = monthly_data['price_peak_fix'][6] - monthly_data['price_peak_fix'][1]
monthly_data['summer_shock_diff_var'] = monthly_data['price_peak_var'][6] - monthly_data['price_peak_var'][1]

# winter shock diff (june to dec)
monthly_data['winter_shock_diff_fix'] = monthly_data['price_peak_fix'][12] - monthly_data['price_peak_fix'][6]
monthly_data['winter_shock_diff_var'] = monthly_data['price_peak_var'][12] - monthly_data['price_peak_var'][6]

In [6]:
display(monthly_data.head())
print(monthly_data.info())

                                 price_mid_peak_fix                        \
month                                             1          2          3
id
0002203ffbb812588b632b9e628cc38d          16.226389  16.226389  16.291555
0004351ebdd665e6ee664792efc4fd13           0.000000   0.000000   0.000000
0010bcc39e42b3c2131ed2ce55246e3c           0.000000   0.000000   0.000000
0010ee3855fdea87602a5b7aba8e42de          16.226389  16.226389  16.226389
00114d74e963e47177db89bc70108537           0.000000   0.000000   0.000000

                                                                              \
month                                     4          5          6          7
id
0002203ffbb812588b632b9e628cc38d  16.291555  16.291555  16.291555  16.291555
0004351ebdd665e6ee664792efc4fd13   0.000000   0.000000   0.000000   0.000000
0010bcc39e42b3c2131ed2ce55246e3c   0.000000   0.000000   0.000000   0.000000
0010ee3855fdea87602a5b7aba8e42de  16.226389  16.226389  16.226383  16.291555
00114d74e963e47177db89bc70108537   0.000000   0.000000   0.000000   0.000000

                                                                   ...  \
month                                     8          9         10  ...
id                                                                 ...
0002203ffbb812588b632b9e628cc38d  16.291555  16.291555  16.291555  ...
0004351ebdd665e6ee664792efc4fd13   0.000000   0.000000   0.000000  ...
0010bcc39e42b3c2131ed2ce55246e3c   0.000000   0.000000   0.000000  ...
0010ee3855fdea87602a5b7aba8e42de  16.291555  16.291555  16.291555  ...
00114d74e963e47177db89bc70108537   0.000000   0.000000   0.000000  ...

                                 peak_off_peak_dec_diff_fix  \
month
id
0002203ffbb812588b632b9e628cc38d                 -16.291555
0004351ebdd665e6ee664792efc4fd13                 -44.444710
0010bcc39e42b3c2131ed2ce55246e3c                 -45.944710
0010ee3855fdea87602a5b7aba8e42de                 -16.291555
00114d74e963e47177db89bc70108537                 -44.266930

                                 peak_off_peak_dec_diff_var  \
month
id
0002203ffbb812588b632b9e628cc38d                  -0.018233
0004351ebdd665e6ee664792efc4fd13                  -0.143943
0010bcc39e42b3c2131ed2ce55246e3c                  -0.201280
0010ee3855fdea87602a5b7aba8e42de                  -0.017683
00114d74e963e47177db89bc70108537                  -0.145440

                                 peak_off_peak_jan_diff_fix  \
month
id
0002203ffbb812588b632b9e628cc38d                 -16.226389
0004351ebdd665e6ee664792efc4fd13                 -44.266931
0010bcc39e42b3c2131ed2ce55246e3c                 -44.444710
0010ee3855fdea87602a5b7aba8e42de                 -16.226389
00114d74e963e47177db89bc70108537                 -44.266931

                                 peak_off_peak_jan_diff_var  \
month
id
0002203ffbb812588b632b9e628cc38d                  -0.022123
0004351ebdd665e6ee664792efc4fd13                  -0.148047
0010bcc39e42b3c2131ed2ce55246e3c                  -0.150837
0010ee3855fdea87602a5b7aba8e42de                  -0.022581
00114d74e963e47177db89bc70108537                  -0.149434

                                 dec_jan_agg_diff_fix dec_jan_agg_diff_var  \
month
id
0002203ffbb812588b632b9e628cc38d             0.325831            -0.005007
0004351ebdd665e6ee664792efc4fd13             0.177779            -0.004104
0010bcc39e42b3c2131ed2ce55246e3c             1.500000             0.050443
0010ee3855fdea87602a5b7aba8e42de             0.325831            -0.014375
00114d74e963e47177db89bc70108537            -0.000001            -0.003994

                                 summer_shock_diff_fix summer_shock_diff_var  \
month
id
0002203ffbb812588b632b9e628cc38d              0.097749              0.001867
0004351ebdd665e6ee664792efc4fd13              0.000000              0.000000
0010bcc39e42b3c2131ed2ce55246e3c              0.000000              0.000000
0010ee3855fdea87602a5b7aba8e42de             -0.000003              0.000000
00114d74e963e47177db89bc70108537              0.000000              0.000000

                                 winter_shock_diff_fix winter_shock_diff_var
month
id
0002203ffbb812588b632b9e628cc38d              0.000000             -0.004169
0004351ebdd665e6ee664792efc4fd13              0.000000              0.000000
0010bcc39e42b3c2131ed2ce55246e3c              0.000000              0.000000
0010ee3855fdea87602a5b7aba8e42de              0.097752             -0.005120
00114d74e963e47177db89bc70108537              0.000000              0.000000

[5 rows x 88 columns]

<class 'pandas.core.frame.DataFrame'>
Index: 15990 entries, 0002203ffbb812588b632b9e628cc38d to ffff7fa066f1fb305ae285bb03bf325a
Data columns (total 88 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   (price_mid_peak_fix, 1)         15990 non-null  float64
 1   (price_mid_peak_fix, 2)         15990 non-null  float64
 2   (price_mid_peak_fix, 3)         15990 non-null  float64
 3   (price_mid_peak_fix, 4)         15990 non-null  float64
 4   (price_mid_peak_fix, 5)         15990 non-null  float64
 5   (price_mid_peak_fix, 6)         15990 non-null  float64
 6   (price_mid_peak_fix, 7)         15990 non-null  float64
 7   (price_mid_peak_fix, 8)         15990 non-null  float64
 8   (price_mid_peak_fix, 9)         15990 non-null  float64
 9   (price_mid_peak_fix, 10)        15990 non-null  float64
 10  (price_mid_peak_fix, 11)        15990 non-null  float64
 11  (price_mid_peak_fix, 12)        15990 non-null  float64
 12  (price_mid_peak_var, 1)         15990 non-null  float64
 13  (price_mid_peak_var, 2)         15990 non-null  float64
 14  (price_mid_peak_var, 3)         15990 non-null  float64
 15  (price_mid_peak_var, 4)         15990 non-null  float64
 16  (price_mid_peak_var, 5)         15990 non-null  float64
 17  (price_mid_peak_var, 6)         15990 non-null  float64
 18  (price_mid_peak_var, 7)         15990 non-null  float64
 19  (price_mid_peak_var, 8)         15990 non-null  float64
 20  (price_mid_peak_var, 9)         15990 non-null  float64
 21  (price_mid_peak_var, 10)        15990 non-null  float64
 22  (price_mid_peak_var, 11)        15990 non-null  float64
 23  (price_mid_peak_var, 12)        15990 non-null  float64
 24  (price_off_peak_fix, 1)         15990 non-null  float64
 25  (price_off_peak_fix, 2)         15990 non-null  float64
 26  (price_off_peak_fix, 3)         15990 non-null  float64
 27  (price_off_peak_fix, 4)         15990 non-null  float64
 28  (price_off_peak_fix, 5)         15990 non-null  float64
 29  (price_off_peak_fix, 6)         15990 non-null  float64
 30  (price_off_peak_fix, 7)         15990 non-null  float64
 31  (price_off_peak_fix, 8)         15990 non-null  float64
 32  (price_off_peak_fix, 9)         15990 non-null  float64
 33  (price_off_peak_fix, 10)        15990 non-null  float64
 34  (price_off_peak_fix, 11)        15990 non-null  float64
 35  (price_off_peak_fix, 12)        15990 non-null  float64
 36  (price_off_peak_var, 1)         15990 non-null  float64
 37  (price_off_peak_var, 2)         15990 non-null  float64
 38  (price_off_peak_var, 3)         15990 non-null  float64
 39  (price_off_peak_var, 4)         15990 non-null  float64
 40  (price_off_peak_var, 5)         15990 non-null  float64
 41  (price_off_peak_var, 6)         15990 non-null  float64
 42  (price_off_peak_var, 7)         15990 non-null  float64
 43  (price_off_peak_var, 8)         15990 non-null  float64
 44  (price_off_peak_var, 9)         15990 non-null  float64
 45  (price_off_peak_var, 10)        15990 non-null  float64
 46  (price_off_peak_var, 11)        15990 non-null  float64
 47  (price_off_peak_var, 12)        15990 non-null  float64
 48  (price_peak_fix, 1)             15990 non-null  float64
 49  (price_peak_fix, 2)             15990 non-null  float64
 50  (price_peak_fix, 3)             15990 non-null  float64
 51  (price_peak_fix, 4)             15990 non-null  float64
 52  (price_peak_fix, 5)             15990 non-null  float64
 53  (price_peak_fix, 6)             15990 non-null  float64
 54  (price_peak_fix, 7)             15990 non-null  float64
 55  (price_peak_fix, 8)             15990 non-null  float64
 56  (price_peak_fix, 9)             15990 non-null  float64
 57  (price_peak_fix, 10)            15990 non-null  float64
 58  (price_peak_fix, 11)            15990 non-null  float64
 59  (price_peak_fix, 12)            15990 non-null  float64
 60  (price_peak_var, 1)             15990 non-null  float64
 61  (price_peak_var, 2)             15990 non-null  float64
 62  (price_peak_var, 3)             15990 non-null  float64
 63  (price_peak_var, 4)             15990 non-null  float64
 64  (price_peak_var, 5)             15990 non-null  float64
 65  (price_peak_var, 6)             15990 non-null  float64
 66  (price_peak_var, 7)             15990 non-null  float64
 67  (price_peak_var, 8)             15990 non-null  float64
 68  (price_peak_var, 9)             15990 non-null  float64
 69  (price_peak_var, 10)            15990 non-null  float64
 70  (price_peak_var, 11)            15990 non-null  float64
 71  (price_peak_var, 12)            15990 non-null  float64
 72  (dec_jan_off_peak_diff_fix, )   15990 non-null  float64
 73  (dec_jan_off_peak_diff_var, )   15990 non-null  float64
 74  (dec_jan_mid_peak_diff_fix, )   15990 non-null  float64
 75  (dec_jan_mid_peak_diff_var, )   15990 non-null  float64
 76  (dec_jan_peak_diff_fix, )       15990 non-null  float64
 77  (dec_jan_peak_diff_var, )       15990 non-null  float64
 78  (peak_off_peak_dec_diff_fix, )  15990 non-null  float64
 79  (peak_off_peak_dec_diff_var, )  15990 non-null  float64
 80  (peak_off_peak_jan_diff_fix, )  15990 non-null  float64
 81  (peak_off_peak_jan_diff_var, )  15990 non-null  float64
 82  (dec_jan_agg_diff_fix, )        15990 non-null  float64
 83  (dec_jan_agg_diff_var, )        15990 non-null  float64
 84  (summer_shock_diff_fix, )       15990 non-null  float64
 85  (summer_shock_diff_var, )       15990 non-null  float64
 86  (winter_shock_diff_fix, )       15990 non-null  float64
 87  (winter_shock_diff_var, )       15990 non-null  float64
dtypes: float64(88)
memory usage: 10.9+ MB
None

- We have successfully added multiple features using contextual interactions between variables. Comparing the difference in both the fixed and variable price of service between january and december, as well as summer shock and winter shock, including the aggregate price differences of all peaks between december and january.